#!/bin/bash

ROOT_SPACE=$(df -h / | sed 's:\s\+:\t:g' | sed -n 2p | cut -f4)
HOME_SPACE=$(df -h /home | sed 's:\s\+:\t:g' | sed -n 2p | cut -f4)

ROOT_LETTER=$(echo $ROOT_SPACE | awk '{print substr($0,length,1)}')
ROOT_LETTER+="b"
HOME_LETTER=$(echo $HOME_SPACE | awk '{print substr($0,length,1)}')
HOME_LETTER+="b"

ROOT_SPACE=$(echo $ROOT_SPACE | sed 's/.$//')
HOME_SPACE=$(echo $HOME_SPACE | sed 's/.$//')

echo -n "<span font_desc='Font Awesome 5 Free 10' rise='2000'>   </span><span font_desc='Comfortaa Bold 10' rise='1000'>$ROOT_SPACE $ROOT_LETTER  ~  </span><span font_desc='Font Awesome 5 Free 10' rise='2000'> </span><span font_desc='Comfortaa Bold 10' rise='1000'>$HOME_SPACE $HOME_LETTER</span> "
