#!/bin/bash
#
# Copyright 2014 Pierre Mavro <deimos@deimos.fr>
# Copyright 2014 Vivien Didelot <vivien@didelot.org>
# Copyright 2014 Andreas Guldstrand <andreas.guldstrand@gmail.com>
#
# Licensed under the terms of the GNU GPL v3, or any later version.

cpu_usage=$[100-$(vmstat 1 2|tail -1|awk '{print $15}')]

echo "<span font_desc='Font Awesome 5 Free 10' rise='2500'>  </span><span font_desc='Comfortaa Bold 10' rise='2000'>$cpu_usage%  </span>"
