#!/bin/bash
TEMPERATURE=$(sensors | grep "Package id 0" | sed -n 1p | sed 's:\s\+:\t:g' | cut -f4 | cut -c2-)

echo -n "<span font_desc='Font Awesome 5 Free 10' rise='3500'>   </span><span font_desc='Comfortaa Bold 10' rise='3500'>$TEMPERATURE   </span>"
