#!/bin/bash
BACKLIGHT_NUM=$(xbacklight | cut -d '.' -f1)

echo -n "<span font_desc='Font Awesome 5 Free 10' rise='3500'>   </span><span font_desc='Comfortaa Bold 10' rise='3500'>$BACKLIGHT_NUM   </span>"
