#!/bin/bash

ROOT_SPACE=$(df -h / | sed 's:\s\+:\t:g' | sed -n 2p | cut -f4)
HOME_SPACE=$(df -h /home | sed 's:\s\+:\t:g' | sed -n 2p | cut -f4)

echo -n "<span font_desc='Ubuntu 10'>   $ROOT_SPACE  ~    $HOME_SPACE   </span>"

