#!/bin/bash
VOLUME_PERCENT=$(amixer sget Master | grep 'Right:' | awk -F'[][]' '{ print $2 }')
NUMBER_PERCENT=$(echo "${VOLUME_PERCENT//%}")

function get_volume_icon {
  if [[ $NUMBER_PERCENT -gt 75 ]]; then
    echo -n ""
  elif [[ $NUMBER_PERCENT -gt 25 ]]; then
    echo -n ""
  elif [[ $NUMBER_PERCENT -gt 1 ]]; then
    echo -n ""
  else
    echo -n ""
  fi
}

echo -n "<span font_desc='Font Awesome 5 Free 10' rise='3500'>  $(get_volume_icon) </span><span font_desc='Comfortaa Bold 10' rise='3500'>$VOLUME_PERCENT   </span>"
