#!/bin/bash
# Ask for sudo
if [ $EUID != 0 ]; then
    sudo "$0" "$@"
    exit $?
fi

set -eu

snap list --all | awk '/disabled/{print $1, $3}' |
    while read snapname revision; do
        snap remove "$snapname" --revision="$revision"
    done
