#!/bin/bash
# Ask for sudo
if [ $EUID != 0 ]; then
    sudo "$0" "$@"
    exit $?
fi

set -eu

# Update
apt update
apt upgrade -y

# Cleanup
bash $HOME/.bin/removeSnaps
bash $HOME/.bin/cleanupDeb

# Notify i3blocks the update is done
pkill -RTMIN+12 i3blocks
