#!/bin/bash
# Ask for sudo
if [ $EUID != 0 ]; then
    sudo "$0" "$USER"
    exit $?
fi

set -eu

# Update
apt update
apt upgrade -y

# Cleanup
bash /home/$1/.local/bin/removeSnaps
bash /home/$1/.local/bin/cleanupDeb

# Notify i3blocks the update is done
pkill -RTMIN+12 i3blocks
