#!/bin/bash
# Ask for sudo
if [ $EUID != 0 ]; then
    sudo "$0" "$@"
    exit $?
fi

set -eu

# Update
apt update
apt upgrade -y

#Cleanup packages
apt remove -y --purge
apt autoremove -y --purge

# Notify i3blocks the update is done
pkill -RTMIN+12 i3blocks

